[package]
name = "pbft-consensus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34"
tokio = { version = "1.20.1", features = ["full"] }
thiserror = "1.0.31"